### ISSUE TITLE
Query data in Nextjs

### ISSUE THREAD

**Issue by cdedreuille** [gbibeaul/use-supabase#2]
What would be the best way to query data in a Nextjs app?

It seems that you still need to wrap the query in an async function unless I'm missing something? Perhaps an example on how to use the query could help.

It would be great if we could do something like ` const { data, loading } = useSupabase(query)`

**Comment by gbibeaul** [comment]
The best way to query will depend on your usecase since Next.js supports multiple was to generate pages.

**Get static props and get server side props**

Can't rely on the react context since. This needs to call data directly via the initialized supabase client. I suggest exporting the client from a config file. This way you can import it to pass it to your context as well as use it in getStaticProps

**Client side fetching**

You can use the pass the use the hooks provided by the lib from components if ever you need to send a query or auth actions.  In my upcoming update I introduce a useTable hook that has a similar API to your example. I decided to create multiple hooks for fetching since queries are built with method chaining in supabase and I could not fit all the different queries in a single hook. 

I'll close this issue in favor of #1 since it's a similar feature request. Next update also will add better documentation on usage in next.js
